# .pre-commit-config.yaml
repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6  # Use a specific version of clang-format
    hooks:
    -   id: clang-format
        types_or: [c++, c, cuda]
